### ISSUE TITLE
Photo for Cabling Waveshare RS485 to RJ45 Ethernet Converter to SysBus Rehau NEA smart 2.0

### ISSUE THREAD

**Issue by MorreMor** [MatteoManzoni/RehauNeasmart2.0_Gateway#4]
Hi Matteo,
thx for your great work! I bought the Hardware but can you make a photo pls für cabling Waveshare to sys bus? I will be nice so I can start tomorrow. Thx

**Comment by MatteoManzoni** [comment]
Hi @MorreMor,
I'll be out of the country for the rest of the week.
Once I'm back I'll add both wiring pictures and modbus gateway configuration screenshots.

Best,
Matteo

**Comment by MorreMor** [comment]
Hi Mattheo, I hope you have a nice Trip? I need Pictures, because I have killed my Smart 2.0 and now I need a New one :-D

**Comment by MatteoManzoni** [comment]
Hey @MorreMor sorry to hear it, [here you can find the documentation](https://github.com/MatteoManzoni/RehauNeasmart2.0_Gateway/blob/main/rehau_neasmart2.0_gateway/waveshare_poegw_howto.md)

**Comment by MorreMor** [comment]
Thx!!But how can i Connect rs485 Converter to my Laptop? I have a mac and cant find my conveeter in my Network. I can Use The Laptop from parents But how i can Connect it? USB converter? Thx dir Yout help Mit freundlichen Grüßen Andreas Morawetz Am 26.06.2023 um 18:54 schrieb Matteo Manzoni ***@***.***>:﻿
Hey @MorreMor sorry to hear it, here you can find the documentation

**Comment by MatteoManzoni** [comment]
I connected it through a PoE switch and then I looked up the DHCP-assigned modbus GW IP on my firewall.
I'm sorry but without having the full picture of what you're trying to do is a bit hard for me to help you, do you already have the gateway in your hands? Is the gateway connected to a PoE switch and powered on? Can you connect to the GW?

**Comment by MorreMor** [comment]
Hi yes Herr it is. I Know my fail i why my Rehau is down. I put gnd to gnd and puff 😅. GW is on Lan But i cant find the ip adress on my Fritz Box. Over parallels vircom i cant find the device. I Dont know what i should do.Mit freundlichen Grüßen Andreas Morawetz Am 26.06.2023 um 19:31 schrieb Matteo Manzoni ***@***.***>:﻿
I connected it through a PoE switch and then I looked up the DHCP-assigned modbus GW IP on my firewall.
I'm sorry but without having the full picture of what you're trying to do is a bit hard for me to help you, do you already have the gateway in your hands? Is the gateway connected to a PoE switch and powered on? Can you connect to the GW?

**Comment by MatteoManzoni** [comment]
I had more or less the same connectivity issue when I got mine, the default ip is 192.168.1.254 despite what the documentation says

**Comment by MorreMor** [comment]
No it isn’t - can geht the website :-(
And can’t find it in my network

Mit freundlichen Grüßen

Andreas Morawetz




> Am 26.06.2023 um 19:42 schrieb Matteo Manzoni ***@***.***>:
> 
> 192.168.1.254

**Comment by MatteoManzoni** [comment]
[May you follow the documentation here on how to reset the network configuration of the gateway?](https://www.waveshare.com/wiki/RS485_TO_POE_ETH_(B))

**Comment by MorreMor** [comment]
But how I can connect from vircom to GW? Must put it in my laptop trough a usb to rs485?
Or can I connect via Lan?

Mit freundlichen Grüßen

Andreas Morawetz

**Comment by MatteoManzoni** [comment]
You need to connect to it through your existing network infrastructure as PoE is required for the gateway to work

**Comment by MorreMor** [comment]
I try, but I don’t find the ip address in my network :-(
The GW blinks green in the housing (not in link)

No device found 

￼

Mit freundlichen Grüßen

Andreas Morawetz

**Comment by MorreMor** [comment]
￼Must be the gw connect to Rehau before I can find it or
Can I find it without?
Maybe I can try this one? 

Or can I buy a programmed RS485 GW from you :-D?
With all right settings :-D?

Mit freundlichen Grüßen

Andreas Morawetz

**Comment by MatteoManzoni** [comment]
You should be able to get hold of the gw before connecting to the Rehau sysbus, is the gw powered and are the lights on?

**Comment by MorreMor** [comment]
Yes Power is red and Link is green Mit freundlichen Grüßen Andreas Morawetz Am 26.06.2023 um 18:54 schrieb Matteo Manzoni ***@***.***>:﻿
Hey @MorreMor sorry to hear it, here you can find the documentation

**Comment by MatteoManzoni** [comment]
What's your router addressing? it should be 192.168.1.0/24 to be in the same subnet space as the gw

**Comment by MorreMor** [comment]
Adress is 192.168.178.1 from my Router.Mit freundlichen Grüßen Andreas Morawetz Am 26.06.2023 um 22:09 schrieb Matteo Manzoni ***@***.***>:﻿
What's your router addressing? it should be 192.168.1.0/24 to be in the same subnet space as the gw

**Comment by MatteoManzoni** [comment]
Ok, can you connect your pc to your router and set a static ip in the 192.168.1.0/24 subnet on your pc?
This way you should be able to reach the gw on 192.168.1.254

**Comment by MorreMor** [comment]
Good morning,
Yesterday I managed to find the converter via the IP 192.168.178.254. (But only via the web interface). However, only via direct LAN connection between PC and converter. I have made the following settings via the web interface in order to access it via the network. (No success) Gateway = Fritz box address? Network is the IP address where it is found on the network? Destination IP is the address of Homeassistant? It would be great if I could access the device without a direct connection. When connecting to the switch, a green lamp flashes in the converter itself (not link or power). This does not flash when there is a direct connection to the PC. Thank you very much in advance. Here's another picture

￼

Mit freundlichen Grüßen

Andreas Morawetz

**Comment by MorreMor** [comment]
Addition:
I finally found it online!
But I can't find it in Vircom to do more setting. Here are two more pictures
￼


￼

Mit freundlichen Grüßen

Andreas Morawetz

**Comment by MatteoManzoni** [comment]
Hi @MorreMor I'm not able to see the pictures

**Comment by MorreMor** [comment]
Mit freundlichen Grüßen Andreas Morawetz Am 27.06.2023 um 09:58 schrieb Matteo Manzoni ***@***.***>:﻿
Hi @MorreMor I'm not able to see the pictures

**Comment by MorreMor** [comment]
Which ip adress Must fill destination ip? Ip from Home Assistant? And in The add on under listening ip adress which ip adress? Local from gateway or destination? Sorry for so much questions  Mit freundlichen Grüßen Andreas Morawetz Am 26.06.2023 um 18:54 schrieb Matteo Manzoni ***@***.***>:﻿
Closed #4 as completed.

**Comment by MatteoManzoni** [comment]
The destination ip should be the ip of the machine running the add-on (typically the machine running homeassistant)
The listening ip should be 0.0.0.0 to listen on all the interfaces of the machine

**Comment by MorreMor** [comment]
NOW it seems to work - in The addon by Home Assistant writes under Protocol get health. Ist this Right? Have no issue Port 502 adress 0.0.0.0. can try when my new Rehau Smart 2.0 is Here:-DMit freundlichen Grüßen Andreas Morawetz Am 27.06.2023 um 11:44 schrieb Matteo Manzoni ***@***.***>:﻿
The destination ip should be the ip of the machine running the add-on (typically the machine running homeassistant)
The listening ip should be 0.0.0.0 to listen on all the interfaces of the machine

**Comment by MatteoManzoni** [comment]
What do you mean by:
>  in The addon by Home Assistant writes under Protocol get health. Ist this Right?

?

**Comment by MorreMor** [comment]
„Get /Health http/1.1 200-127.0.0.1 Ist this ok or wrong This stays unser the addon log How can i See if my parameters / Settings are Right? Mit freundlichen Grüßen Andreas Morawetz Am 27.06.2023 um 15:50 schrieb Matteo Manzoni ***@***.***>:﻿
What do you mean by:

in The addon by Home Assistant writes under Protocol get health. Ist this Right?

?

**Comment by MatteoManzoni** [comment]
That's normal, it's part of the docker healthcheck

**Comment by MatteoManzoni** [comment]
Keep me posted once you'll have the new Neasmart basestation up and running 🤞

**Comment by MorreMor** [comment]
Yes!!!!! Now I had find the Converter into Vircom!!!!!
Now I have a last Question.
All Settings are saved, only the chop box by 
More Advanced Setting -> Enable RS485 bus conflict detection: enabled and 20ms
Cant be saved and when I opens the settings again the chop box is resetet.
Why?….

All other Settings can be done including. This 
More Advanced Setting -> Modbus Gateway Type: Simple Modbus TCP to RTU

The Light of the converter is now blue :-)

Is it bad when the option bus conflict is not chop boxed?
Know you maybe the reason why I can’t save the chop box?

Which button is for save? Modify settings? Or save as default? 
Nothing helps

Thx for your last Answer :-)

Mit freundlichen Grüßen

Andreas Morawetz

**Comment by MatteoManzoni** [comment]
Nice to hear, as to make the settings stick you should:
- modify settings in `More Advanced Settings`
- click on `ok`
- click on `save as default`
- click on `modify settings`

**Comment by MorreMor** [comment]
Its really crazy,
I can change every settings and all saved except the Bus Conflict chop box.
It can’t be saved respectively the settings are lost when I go in settings again.
Maybe this one can only changed when the bus is linked to Rehau smart basis?

Mit freundlichen Grüßen

Andreas Morawetz

**Comment by MatteoManzoni** [comment]
I really don't know, anyway that setting is not fundamental.
Let me know if you have any problem once you connect everything to the rehau system

**Comment by MorreMor** [comment]
Thx very much for all Your help Mit freundlichen Grüßen Andreas Morawetz Am 27.06.2023 um 15:57 schrieb Matteo Manzoni ***@***.***>:﻿
Keep me posted once you'll have the new Neasmart basestation up and running 🤞

**Comment by MorreMor** [comment]
0,8 cable cross-section bus Cabernet ok for sysbus? Mit freundlichen Grüßen Andreas Morawetz Am 28.06.2023 um 08:23 schrieb Matteo Manzoni ***@***.***>:﻿
I really don't know, anyway that setting is not fundamental.
Let me know if you have any problem once you connect everything to the rehau system

**Comment by MatteoManzoni** [comment]
Hey @MorreMor, the cable ideally should be: `JY(ST)Y 2x2x0,8mm`
That means 2 twisted pairs with grounded shielding and plastic liner and Kl.1 conductors.
Skipping on twisting and shielding with reduce the signal quality

**Comment by MorreMor** [comment]
Hi my Friend,

Now I have my new Rehau nea smart 2.0 system.
I have configured my waveshare.

I have cabled all right now, but I cant find devices.

Questitons:

Destination IP from Waveshare ist the Ip from Homeassistant, = Raspberry?
Destination Port is what? Port of Homeassistant or simple 502?

In The Add on:

Listen Adress is what for IP? 
Listen Port is which Port?

Pls help me

Thx very much

Mit freundlichen Grüßen

Andreas Morawetz

**Comment by MorreMor** [comment]
The sys bus led from REHAU Nea smart 2.0 blinks, so it works but
I cant find devices.

I don’t know why :-( 

Mit freundlichen Grüßen

Andreas Morawetz

**Comment by MorreMor** [comment]
Maybe you can give a an mail address who I can send you screenshots
From all my settings? (Waveshare, my Ip adreses and Add on Settings?

Mit freundlichen Grüßen

Andreas Morawetz

**Comment by MorreMor** [comment]
The problem is, the add on works
But I can find devices.

Where are the devices? I installed the add on and restart the homeassistant
But I cant add the integration because there is no one
And I cant find anything :-( 
Mit freundlichen Grüßen

Andreas Morawetz

**Comment by MatteoManzoni** [comment]
Hey @MorreMor, you can post the configuration here if nothing sensitive is present.
I think all the question you asked me are documented here: https://github.com/MatteoManzoni/RehauNeasmart2.0_Gateway/blob/main/rehau_neasmart2.0_gateway/waveshare_poegw_howto.md

**Comment by MatteoManzoni** [comment]
Anyway my email is: manzoni.matteo@mailfence.com

**Comment by MorreMor** [comment]
I have Send you an email with Screenshots ***@***.*** freundlichen Grüßen Andreas Morawetz Am 25.07.2023 um 09:58 schrieb Matteo Manzoni ***@***.***>:﻿
Anyway my email is: ***@***.***

**Comment by MorreMor** [comment]
Good morning,

Is it possible to get in HomeKit the havcs mode off and heat?
There is actually only auto.
This will be nice!

Mit freundlichen Grüßen

Andreas Morawetz

**Comment by MorreMor** [comment]
Pls help me. Pls ….
See issue on github NEA Smart 2.0
Mit freundlichen Grüßen 

Andreas Morawetz
