### ISSUE TITLE
Question: Identify Rehau system connections

### ISSUE THREAD

**Issue by zbuh** [MatteoManzoni/RehauNeasmart2.0_Gateway#7]
My System seems a little different from yours. I have 3 panels (on in each floor), the main one is the one in the pictures.
I think that modes is already used to "talk" with other panels.

It seems to be one connection still available on the left. Is that one that should be used ?

Thanks

![IMG_0251](https://github.com/MatteoManzoni/RehauNeasmart2.0_Gateway/assets/190734/97bec497-b855-451a-bcda-0f9558589071)
![IMG_0252](https://github.com/MatteoManzoni/RehauNeasmart2.0_Gateway/assets/190734/afe0eaa2-cea5-4810-9c57-be69f0b91dbe)

**Comment by MatteoManzoni** [comment]
Hey @zbuh you should be able to connect the gateway to the spare sysbus connection:
![261375830-afe0eaa2-cea5-4810-9c57-be69f0b91dbe](https://github.com/MatteoManzoni/RehauNeasmart2.0_Gateway/assets/35832688/152a24d7-e182-452e-b7c2-5a319b364a0c)

**Comment by zbuh** [comment]
yep. that was what I assumed. Thanks. 
Ordering parts... POE 2 port switch and Modbus adapter...
